### PR TITLE
fix: add fluid.css to uioStyles shortcode and add shortcode for CSS Custom Props (resolves #81)

### LINKED ISSUE #81: Add fluid.css to uioStyles shortcode
## Describe the bug
UI Options requires some styling from `framework/core/css/fluid.css` in order to apply certain UIO styles. For example, focus contrast styling requires `fl-focus` which is a style found in `fluid.css`.

Otherwise it is up to the integrator to understand this relationship and to manually include `fluid.css`.

### PR DESCRIPTION
**Pull request by jobara**
Resolves #81

### CODE REVIEW

**Review by greatislander — COMMENTED** [review]
~Is `fluid.css` not needed when using props to build a custom integration?~

Edit: saw your comment on the issue, never mind!

File: src/shortcodes/uio.js [hunk 1]
```diff
@@ -13,7 +13,13 @@ https://github.com/fluid-project/eleventy-plugin-fluid/raw/main/LICENSE.md.
 
 module.exports = {
     uioStyles: function () {
-        return `<link href="/lib/infusion/src/framework/preferences/css/Enactors.css" rel="stylesheet">
+        return `<link href="/lib/infusion/src/framework/core/css/fluid.css" rel="stylesheet">
+    <link href="/lib/infusion/src/framework/preferences/css/Enactors.css" rel="stylesheet">
+    <link href="/lib/infusion/src/framework/preferences/css/PrefsEditor.css" rel="stylesheet">
+    <link href="/lib/infusion/src/framework/preferences/css/SeparatedPanelPrefsEditor.css" rel="stylesheet">`;
+    },
+    uioStylesProps: function () {
```
Comment (greatislander) [inline src/shortcodes/uio.js:21]:
```suggestion
    uioStyleProps: function () {
```

**Review by greatislander — CHANGES_REQUESTED** [review]

**Review by greatislander — APPROVED** [review]
